### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by PowerPress** [gauss314/defi#12]
Received the following error:

>>> pair = ['ethereum','nexus-governance-token']
>>> apr = 553.94
>>> dft.farmSimulate(pair, apr, start='2021-11-30')
Downloading ethereum
Downloading nexus-governance-token
Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    dft.farmSimulate(pair, apr, start='2021-11-30')
  File "C:\Users\jadmin\AppData\Local\Programs\Python\Python39\lib\site-packages\defi\defi_tools.py", line 276, in farmSimulate
    farm = farm.divide(farm.iloc[0])
  File "C:\Users\jadmin\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\jadmin\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Users\jadmin\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by gauss314** [comment]
Maybe it was a fail in coingecko API, now this example is working ok
