### ISSUE TITLE
dft.geckoHistorical('bitcoin')

### ISSUE THREAD

**Issue by gumartinez** [gauss314/defi#8]
Buenas, intento correr el codigo en Spyder:

 dft.geckoHistorical('bitcoin')

y me da el error 

dft.geckoHistorical('bitcoin')
Traceback (most recent call last):

  File "<ipython-input-20-9e94219a4ed5>", line 1, in <module>
    dft.geckoHistorical('bitcoin')

  File "C:\Users\gmartinez\Anaconda3\lib\site-packages\defi\defi_tools.py", line 227, in geckoHistorical
    df[0] = pd.to_datetime(df[0], unit='ms')

  File "C:\Users\gmartinez\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2938, in __setitem__
    self._set_item(key, value)

  File "C:\Users\gmartinez\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3001, in _set_item
    NDFrame._set_item(self, key, value)

  File "C:\Users\gmartinez\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3624, in _set_item
    self._data.set(key, value)

  File "C:\Users\gmartinez\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1086, in set
    for blkno, val_locs in libinternals.get_blkno_placements(blknos, group=True):

  File "pandas\_libs\internals.pyx", line 448, in get_blkno_placements

  File "pandas\_libs\internals.pyx", line 352, in pandas._libs.internals.get_blkno_indexers

ValueError: Buffer has wrong number of dimensions (expected 1, got 0)

Cuando lo hago en colab no me sucede esto.

**Comment by gauss314** [comment]
Es alguna actualizacion de pandas de tu anaconda local, por eso no tenes el error en colab, te sugiero abrir el anaconda prompt y ejecutar esto:

conda update --all


va a tardar 15 minutos pero luego de eso deberia andar bien

**Comment by gauss314** [comment]
Anda borrando lineas de abajo hacia arriba a ver cual es la conflictiva, es raro a mi me corre lo mas bien, seguro es alguna libreria en tu instalacion que te esta generando un conflicto

**Comment by davenalonell26** [comment]
The `ValueError: Buffer has wrong number of dimensions (expected 1, got 0)` suggests that the DataFrame `df` might be empty or incorrectly structured when trying to set `df[0]`. You could add a check to see what `df` contains right before that line in `geckoHistorical` to diagnose if the data is being fetched properly.

**Comment by jasamayco26** [comment]
The `ValueError: Buffer has wrong number of dimensions (expected 1, got 0)` hits exactly when setting `df[0]` in geckoHistorical after the DataFrame is built from the bitcoin historical data. 
The fact that it only fails in the Anaconda Spyder env suggests the response from the call might not be getting unpacked the same way as in Colab, so logging the raw json before pd.DataFrame would be the next step to check.

**Comment by tearsaalainah26** [comment]
The traceback in `defi_tools.py` at line 227 suggests that `df[0]` is returning a scalar or an empty structure rather than the expected Series, which is likely caused by the CoinGecko API returning an empty response or a different JSON schema than your local environment expects. Since this works in Colab but not your local Anaconda install, check the output of your API request before the conversion by adding `print(df)` right before the `pd.to_datetime` line to verify if the DataFrame is being populated correctly. If `df` is empty, the `ValueError` during the slice assignment makes sense, which could indicate a dependency version mismatch—specifically with `requests` or `pandas`—that is handled differently by your local environment's current state.
